### ISSUE TITLE
ByBit Brokerage

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#1525]
#### Expected Behavior
ByBit brokerage is fully documented.

#### Actual Behavior
New brokerage support, so not documented yet.

#### TODO:
- [ ] Cloud Platform
- [ ] Writing Algorithms
- [ ] Lean CLI
See https://github.com/QuantConnect/Lean.Brokerages.ByBit/pull/10

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
